### ISSUE TITLE
add new route to make docker containers connect to each other

### ISSUE THREAD

**Issue by VC1664** [NordSecurity/libtelio#10]
In addition to set up the ip address as mentioned in README, I also have to add a new route with the following command to make t1 and t2 connect to each other:
```
ip route add 100.64.0.0/10 via <IP_ADDRESS> dev <NAME>
```

**Comment by Jauler** [comment]
Hi,

Good catch!

One more way to update the README would be to specify the IP in CIDR notation. In this case, the ip-utils will add route automatically, like this:
```bash
ip addr add <IP_ADDRESS>/10 dev <NAME>
```
I will update the README

**Comment by Jauler** [comment]
Readme is updated -> closing issue
