### ISSUE TITLE
raspberry pi - 6.1.19-

### ISSUE THREAD

**Issue by bjlockie** [NordSecurity/libtelio#2]
`nordvpnd[500]: 2023/03/16 17:12:32 [Error] TELIO: libtelio-build/libtelio/crates/telio-wg/src/adapter/linux_native_wg.rs:102 LinuxNativeWg: [GET01] Unable to get interface from WireGuard. Make sure it exists and you have permissions to access it. `

**Comment by bjlockie** [comment]
It is 6.1.19.
It'll be the next version of RaspbianOS.
I need that kernel because it supports my mt7921au wifi.
They might update the kernel if there are problems.

Mar. 17, 2023 06:00:30 Rytis Karpuška ***@***.***>:

**Comment by Jauler** [comment]
hmm, are You able to use regular WireGuard (via the `wg-tools`) on that RPi? 

e.g. executing these quick starting guides: https://www.wireguard.com/quickstart/

**Comment by bjlockie** [comment]
The official kernerl of raspbianos is 6.1.19 now and wireguard works with nordvpn.
